<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\OptionSharp\OptionSharp.csproj"/>
        <ProjectReference Include="..\OptionSharp.SourceGen\OptionSharp.SourceGen.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="System.Linq.Async" Version="6.0.1"/>
<!--        <PackageReference Include="OptionSharp" Version="0.3.0-g678927b66e" />-->
    </ItemGroup>

</Project>
