# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    defaults:
      run:
        working-directory: ./src
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal

  pack:
    if: github.ref == 'refs/heads/main'
    needs: test
    defaults:
      run:
        working-directory: ./src
    runs-on: ubuntu-latest
    steps:
      - name: Pack
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Upload nuget package
        uses: actions/upload-artifact@v3
        with:
          name: nupkg
          path: |
            src/OptionSharp/bin/Release/*.nupkg
    
