# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  pull-requests: write

jobs:
  test:
    defaults:
      run:
        working-directory: ./src
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
    
    - name: Install Report Generator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    - name: Generate Code Coverage Summary
      run: reportgenerator -reports:"./coverage/**/coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:"MarkdownSummaryGithub;Badges"

    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: ./src/coverage/SummaryGithub.md
        
    - name: Upload badge
      #if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: coverage=badge
        path: |
          ./src/coverage/badge_shieldsio_linecoverage_blue.svg

    - name: Pack
      run: dotnet pack -c Release --no-build --verbosity normal
      
    - name: Upload nuget package
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: |
          ./src/OptionSharp/bin/Release/*.nupkg
